openapi: "3.0.0"

info:
  title: "Live Score MMA/Wrestling API"
  version: "1.0"
  description: ""

servers:
  - url: '{custom}'
    variables:
      custom:
        default: https://localhost

externalDocs:
  description: "Find out more about Live Score"
  url: "https://www.live-score-app.com"

paths:

  /version:
    get:
      tags:
        - "Version"
      summary: "Get the API version"
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"

  /data:
    get:
      tags:
        - "Game"
      summary: "Get the data of the current game"
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"

  /game/start:
    post:
      tags:
        - "Game"
      summary: "Starts the current game"
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /game/end:
    post:
      tags:
        - "Game"
      summary: "Ends the current game"
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /game/reset:
    post:
      tags:
        - "Game"
      summary: "Resets the current game. Use this for back-to-back games."
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /scoreboards/toggle:
    post:
      tags:
        - "Game"
      summary: "Shows/Hides the layouts"
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"


  /round/up:
    post:
      tags:
        - "Rounds"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /round/down:
    post:
      tags:
        - "Rounds"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"


  /score/team/1/up:
    post:
      tags:
        - "Team Scores"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /score/team/1/down:
    post:
      tags:
        - "Team Scores"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /score/team/2/up:
    post:
      tags:
        - "Team Scores"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /score/team/2/down:
    post:
      tags:
        - "Team Scores"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /score/fighter/1/up:
    post:
      tags:
        - "Fighter Scores"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /score/fighter/1/down:
    post:
      tags:
        - "Fighter Scores"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /score/fighter/1/reset:
    post:
      tags:
        - "Fighter Scores"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /score/fighter/2/up:
    post:
      tags:
        - "Fighter Scores"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /score/fighter/2/down:
    post:
      tags:
        - "Fighter Scores"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /score/fighter/2/reset:
    post:
      tags:
        - "Fighter Scores"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"


  /game/away/up:
    post:
      tags:
        - "Games"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /game/away/down:
    post:
      tags:
        - "Games"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /game/home/up:
    post:
      tags:
        - "Games"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /game/home/down:
    post:
      tags:
        - "Games"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"


  /time/start:
    post:
      tags:
        - "Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /time/stop:
    post:
      tags:
        - "Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /time/toggle:
    post:
      tags:
        - "Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /time/reset:
    post:
      tags:
        - "Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /time/set:
    post:
      tags:
        - "Time"
      summary: "Sets the game time"
      security:
        - API: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                seconds:
                  default: 60
      responses:
        "200":
          description: "successful operation"
  /time/minutes/up:
    post:
      tags:
        - "Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /time/minutes/down:
    post:
      tags:
        - "Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /time/seconds/up:
    post:
      tags:
        - "Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /time/seconds/down:
    post:
      tags:
        - "Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"


  /shotclock/start:
    post:
      tags:
        - "Shotclock"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /shotclock/stop:
    post:
      tags:
        - "Shotclock"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /shotclock/reset:
    post:
      tags:
        - "Shotclock"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /shotclock/seconds/up:
    post:
      tags:
        - "Shotclock"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /shotclock/seconds/down:
    post:
      tags:
        - "Shotclock"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"


  /ridingtime/fighter/1/start:
    post:
      tags:
        - "Riding Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /ridingtime/fighter/2/start:
    post:
      tags:
        - "Riding Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /ridingtime/minutes/up:
    post:
      tags:
        - "Riding Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /ridingtime/minutes/down:
    post:
      tags:
        - "Riding Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /ridingtime/seconds/up:
    post:
      tags:
        - "Riding Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /ridingtime/seconds/down:
    post:
      tags:
        - "Riding Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /ridingtime/reset:
    post:
      tags:
        - "Riding Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"



components:
  securitySchemes:
    API:
      type: apiKey
      in: header
      name: Authorization
