openapi: "3.0.0"

info:
  title: "Live Score Multi Sport API"
  version: "1.0"
  description: ""

servers:
  - url: '{custom}'
    variables:
      custom:
        default: https://localhost

externalDocs:
  description: "Find out more about Live Score"
  url: "https://www.live-score-app.com"

paths:

  /version:
    get:
      tags:
        - "Version"
      summary: "Get the API version"
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"

  /data:
    get:
      tags:
        - "Game"
      summary: "Get the data of the current game"
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
    post:
      tags:
        - "Game"
      summary: "Sets the data of the current game"
      security:
        - API: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./definitions/multisport.yaml"
      responses:
        "200":
          description: "successful operation"

  /game/start:
    post:
      tags:
        - "Game Flow"
      summary: "Starts the current game"
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /game/end:
    post:
      tags:
        - "Game Flow"
      summary: "Ends the current game"
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /game/reset:
    post:
      tags:
        - "Game Flow"
      summary: "Resets the current game. Use this for back-to-back games."
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /scoreboards/toggle:
    post:
      tags:
        - "Game Flow"
      summary: "Shows/Hides the layouts"
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"


  /period/up:
    post:
      tags:
        - "Periods"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /period/down:
    post:
      tags:
        - "Periods"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"

  /score/away/up:
    post:
      tags:
        - "Scores"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /score/away/down:
    post:
      tags:
        - "Scores"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /score/home/up:
    post:
      tags:
        - "Scores"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /score/home/down:
    post:
      tags:
        - "Scores"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"

  /game/away/up:
    post:
      tags:
        - "Games"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /game/away/down:
    post:
      tags:
        - "Games"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /game/home/up:
    post:
      tags:
        - "Games"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /game/home/down:
    post:
      tags:
        - "Games"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"


  /time/start:
    post:
      tags:
        - "Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /time/stop:
    post:
      tags:
        - "Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /time/toggle:
    post:
      tags:
        - "Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /time/reset:
    post:
      tags:
        - "Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /time/set:
    post:
      tags:
        - "Time"
      summary: "Sets the game time"
      security:
        - API: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                seconds:
                  default: 60
      responses:
        "200":
          description: "successful operation"
  /time/minutes/up:
    post:
      tags:
        - "Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /time/minutes/down:
    post:
      tags:
        - "Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /time/seconds/up:
    post:
      tags:
        - "Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /time/seconds/down:
    post:
      tags:
        - "Time"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"


  /shotclock/start:
    post:
      tags:
        - "Shotclock"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /shotclock/stop:
    post:
      tags:
        - "Shotclock"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /shotclock/reset:
    post:
      tags:
        - "Shotclock"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /shotclock/seconds/up:
    post:
      tags:
        - "Shotclock"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /shotclock/seconds/down:
    post:
      tags:
        - "Shotclock"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /shotclock/visibility/toggle:
    post:
      tags:
        - "Shotclock"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"


  /side/away:
    post:
      tags:
        - "Sides"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"
  /side/home:
    post:
      tags:
        - "Sides"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"


  /buzzer/play:
    post:
      tags:
        - "Buzzer"
      summary: ""
      security:
        - API: [ ]
      responses:
        "200":
          description: "successful operation"


components:
  securitySchemes:
    API:
      type: apiKey
      in: header
      name: Authorization
